"""empty message

Revision ID: 00423c3d6569
Revises: 
Create Date: 2025-03-18 05:01:05.370023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00423c3d6569'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formatos_torneo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('jugadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=180), nullable=True),
    sa.Column('salt', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.Column('nickhabbo', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickhabbo')
    )
    op.create_table('torneos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('modalidad', sa.String(length=50), nullable=False),
    sa.Column('formato', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('convocatorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modalidad', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('jugadores_equipos',
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.PrimaryKeyConstraint('jugador_id', 'equipo_id')
    )
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dt_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('equipo_a_id', sa.Integer(), nullable=False),
    sa.Column('equipo_b_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('juez', sa.String(length=100), nullable=True),
    sa.Column('goles_equipo_a', sa.Integer(), nullable=True),
    sa.Column('goles_equipo_b', sa.Integer(), nullable=True),
    sa.Column('mvp_id', sa.Integer(), nullable=True),
    sa.Column('mencion_equipo_a_id', sa.Integer(), nullable=True),
    sa.Column('mencion_equipo_b_id', sa.Integer(), nullable=True),
    sa.Column('link_video', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_a_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['equipo_b_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['mencion_equipo_a_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['mencion_equipo_b_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['mvp_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadisticas_jugador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('goles', sa.Integer(), nullable=True),
    sa.Column('asistencias', sa.Integer(), nullable=True),
    sa.Column('autogoles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadisticas_jugador')
    op.drop_table('partidos')
    op.drop_table('ofertas')
    op.drop_table('jugadores_equipos')
    op.drop_table('equipos')
    op.drop_table('convocatorias')
    op.drop_table('torneos')
    op.drop_table('jugadores')
    op.drop_table('formatos_torneo')
    op.drop_table('asistencia')
    # ### end Alembic commands ###
