"""Add ON DELETE CASCADE to ofertas.equipo_id

Revision ID: 8626f4d0d5dc
Revises: 
Create Date: 2025-03-29 20:37:33.766618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8626f4d0d5dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.drop_constraint('ofertas_equipo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipos', ['equipo_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ofertas_equipo_id_fkey', 'equipos', ['equipo_id'], ['id'])

    # ### end Alembic commands ###
