"""Add ON DELETE CASCADE to ofertas.equipo_id

Revision ID: cb8586cdc755
Revises: 8626f4d0d5dc
Create Date: 2025-03-29 20:54:09.414488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8586cdc755'
down_revision = '8626f4d0d5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores_equipos', schema=None) as batch_op:
        batch_op.drop_constraint('jugadores_equipos_equipo_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('jugadores_equipos_jugador_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipos', ['equipo_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'jugadores', ['jugador_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores_equipos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('jugadores_equipos_jugador_id_fkey', 'jugadores', ['jugador_id'], ['id'])
        batch_op.create_foreign_key('jugadores_equipos_equipo_id_fkey', 'equipos', ['equipo_id'], ['id'])

    # ### end Alembic commands ###
